Add missing building tags for the test framework
Currently the linter fails with:
framework/conditions.go:12:95: undefined: Condition (typecheck)
package framework

To fix it we need to add missing build tags that we have in other
places.